-- The Twins Coffee® - Supabase SQL Schema
-- Run this in the Supabase SQL Editor

-- 1. Admins Table
CREATE TABLE IF NOT EXISTS admins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Categories Table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ar TEXT,
    slug TEXT UNIQUE NOT NULL,
    image TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Shipping Options Table
CREATE TABLE IF NOT EXISTS shipping_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ar TEXT,
    price NUMERIC DEFAULT 0,
    days TEXT,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Products Table
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    name_ar TEXT,
    category TEXT DEFAULT 'coffee',
    description TEXT,
    badge TEXT,
    has_type BOOLEAN DEFAULT FALSE,
    has_roast BOOLEAN DEFAULT FALSE,
    featured BOOLEAN DEFAULT FALSE,
    active BOOLEAN DEFAULT TRUE,
    images JSONB DEFAULT '[]'::jsonb, -- Array of strings
    variant_images JSONB DEFAULT '{}'::jsonb,
    colors JSONB DEFAULT '[]'::jsonb,
    sizes JSONB DEFAULT '[]'::jsonb, -- Array of size objects
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Orders Table
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    custom_id TEXT UNIQUE NOT NULL, -- e.g. ORD-12345
    customer_name TEXT NOT NULL,
    customer_phone TEXT,
    customer_address TEXT,
    city TEXT,
    items JSONB DEFAULT '[]'::jsonb,
    shipping_id BIGINT REFERENCES shipping_options(id) ON DELETE SET NULL,
    shipping_name TEXT,
    shipping_price NUMERIC DEFAULT 0,
    subtotal NUMERIC NOT NULL,
    total NUMERIC NOT NULL,
    status TEXT DEFAULT 'pending',
    notes TEXT,
    payment_method TEXT DEFAULT 'cod',
    paymob_order_id TEXT,
    paymob_transaction_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Note: Ensure Row Level Security (RLS) is disabled or properly configured for your API.
-- Since the Node.js backend acts as an admin using the service_role key, it will bypass RLS.
